name: Build docker Image

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get short SHA
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV
      - name: Print short SHA
        run: |
          echo "${{ env.SHORT_SHA }}"

      - name: Clone
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/typeling1578/misskey:${{ env.SHORT_SHA }}
